#!/usr/bin/env bash

# This script uses git to sync all documents for each geraldpi-documents
# instance on the network. 


cd /media/documents

if [ $? -ne 0 ] 
then
	echo "USB drive has not been setup yet.  Canclling the sync"
	exit -1
fi

# Initialize the system-wide git config using the unqiue hostname as the username
git config --global ...
git config --global ...
git config --global ...

# Initialize the repo if it has not bee setup yet
git status
if [ $? -ne 0 ] 
then
	git init
fi

# Remove all git remotes from the current repo
git remote remove ...

# Get a list of all gpi-documents devices on the network
avahi...

# Add git remotes for each discovered devices on the network
git remote add ...

# For each remote, perform a git pull


