#!/usr/bin/env bash

# This script uses git to sync all documents for each geraldpi-documents
# instance on the network. 


cd /media/documents

if [ $? -ne 0 ] 
then
	echo "USB drive has not been setup yet.  Canclling the sync"
	exit -1
fi

# If gitconfig does not exist, generate unique email and username based on hostname
if [ ! -f ~/.gitconfig ]
then
git config --global user.email "$( hostname )@home.com"
git config --global user.name "$( hostname )"
fi

# Initialize the repo if it has not bee setup yet
git status
if [ $? -ne 0 ] 
then
	git init
fi

# Remove all git remotes from the current repo
for remote in $( git remote )
do
	git remote remove $remote
done

# Get a list of all gpi-documents devices on the network
for peer in $( find_peers )
do

	# Add git remotes for each discovered devices on the network
	git remote add $peer ssh://root@$peer:/media/documents
done

# For each remote, perform a git pull
for remote in $( git remote )
do

	git pull $peer master

done

