#!/usr/bin/env bash

# THis script uses the SoCs serial number in order to generate a unique
# hostname for the device that will be consistant for a given set of hardware

# This script detects if the hostname is already unqieu and will not attempt to
# rewrite it multiple times

# Get the current hostname
HOSTNAME=$( cat /etc/hostname )

# Get the serial number of the SoC
SERIAL=$( cat /sys/firmware/devicetree/base/serial-number )

# Grab the last 8 digits of the serial and add a dash to be beginning
SUFFIX="-${SERIAL: -8}"


# If the last 9 digits of the hostname matches hte suffix, there is nothing to do
if [ "${SUFFIX: -9}" == "${HOSTNAME: -9}" ]
then
	echo "Hostname is already unique"
else
	echo "Writing New Hostname:"
	echo "$HOSTNAME$SUFFIX" > /etc/hostname
fi


