#!/usr/bin/env bash

# This script will tweak the CPU settings from userspace rather tha modifying
# the default kernel. Right now it just adjusts the governor, but we can do
# more interesting things later


# Set all cores' governor to "OnDemand"
echo ondemand > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor

