#!/usr/bin/env bash

# TODO If no argument is provided, list only peers that have the same base hostname

# TODO if the argument is "all" list all peers.


# Generate a list of hostnames and resolved IPv4 addresses
avahi-browse --parsable --ignore-local --resolve --terminate _ssh._tcp | awk '
BEGIN { FS=";" } 
{
	if ( $1 == "=" && $3 == "IPv4" )
		print $4 " " $8 ;
}'

