#!/usr/bin/env bash


# Generate a list of hostnames and resolved IPv4 addresses
avahi-browse --parsable --ignore-local --resolve --terminate _ssh._tcp | awk '
BEGIN { FS=";" } 
{
	if ( $1 == "=" && $3 == "IPv4" )
		print $4 " " $8 ;
}'

