#!/usr/bin/env bash

# THis script will merge all of the input files into a single PDF

# TODO Verify the output file does not exist
# TODO Verify all the input foes do exist

# Merge
gs -q -sPAPERSIZE=letter -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$1 ${@:2}

git add $1

git rm ${@:2}

git commit -m "Merge multiple pdfs into $1"

