#!/usr/bin/env bash

# THis script will merge all of the input files into a single PDF

# Verify the output file does not exist
# Verify all the input foes do exist

# Merge
gs -q -sPAPERSIZE=letter -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$1 ${@:2}

git add $OUTPUT

git rm $INPUT FILES

git commit -m "Merge multiple files into $1"

